# Build
exclude:
  - Gemfile
  - Gemfile.lock
  - package.json
  - README.md
permalink: /blog/:year/:month/:title
timezone: America/New_York

# Formatting
markdown: redcarpet
redcarpet:
  extensions:
    - :no_intra_emphasis
    - :autolink
    - :superscript
    - :footnotes
highlighter: pygments

# Assets
sass:
  sass_dir: assets/css
